config/routes.rb
SalesManagementR4::Application.routes.draw do
  devise_for :users, controllers: {sessions: "sessions"}   

  root :to => redirect('/dashboard')
  match "/configurations" => "configurations/dashboard#index", via: [:get]

  resources :attendances do
    collection do
      get :get_list
    end
  end 
  resources :helps do
    collection do
    end
  end  

  resources :customers do
    collection do
      get :get_list
      get :filter_choosed_customer
      get :filter_position
    end
  end  

  resources :insentives do
    collection do
      get :get_list
      get :get_sales
      get :export
    end
  end  
  
  namespace :configurations do
    resources :users do
      collection do
        get :search
      end
    end  
    resources :dashboard
    resources :announcements
    resources :quotes do 
      collection do
        post :update_is_active
      end
    end 
    resources :news 
    resources :product_types do
      member do
        get :recover
      end
    end  

    resources :product_categories do
      member do
        get :recover
      end
    end  
    
    resources :report_prospects  do
      member do
        get :recover
      end
    end  

    resources :report_capacities do
      member do
        get :recover
      end
    end  

    resources :payment_types do
      member do
        get :recover
      end
    end  

    resources :office_hours   
  end
  resources :dashboard
  resources :reports do
    collection do
      get :get_customer
      get :filter_choosed
      get :filter_position
      post :set_color
    end
    member do
      get :writer
    end
  end

  resources :histories do
    collection do
    end
    member do
    end
  end

  
end

app/views/layouts/admin/_navbar.html.erb
<!-- navbar -->
<header class="navbar navbar-inverse" role="banner">
  <div class="navbar-header">
    <button class="navbar-toggle" type="button" data-toggle="collapse" id="menu-toggler">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">
      <%= image_tag "/assets/logo.png", :height => "26px;" %>
    </a>
  </div>
  <ul class="nav navbar-nav pull-right hidden-xs">
    <li class="hidden-xs hidden-sm">
      <h1 style="font-size: 1.5em; color:#CCCCCC; margin: 10px 15px;"><%=current_user.name %></h1>
    </li>
    <li class="settings hidden-xs hidden-sm">
      <a href="/helps" role="button">
        <i class="icon-question-sign"></i>
      </a>
    </li>
    <% if(current_user.is_position(ADMINISTRATOR)) %>
      <li class="settings hidden-xs hidden-sm">
        <a href="/configurations" role="button">
          <i class="icon-cog"></i>
        </a>
      </li>
    <% end %>
    <li class="settings hidden-xs hidden-sm">
      <a href="<%=destroy_user_session_path%>" role="button">
        <i class="icon-share-alt"></i>
      </a>
    </li>
  </ul>
</header>
<!-- end navbar -->

app/views/layouts/admin/_sidebar.html.erb
<!-- sidebar -->
<div id="sidebar-nav">
  <ul id="dashboard-menu">
    <li id="sidebar-menu-dashboard" class="sidebar-menu">
      <a href="/dashboard">
        <i class="icon-home"></i>
        <span>Home</span>
      </a>
    </li>
    <li id="sidebar-menu-reports" class="dropdown sidebar-menu">
        <a class="dropdown-toggle" href="/reports/#">
          <i class="icon-edit"></i>
          <span>Laporan</span>
          <i class="icon-chevron-down"></i>
        </a>
        <ul style="display: hide;" class="submenu">
          <li id="list-reports" class="sidebar-menu-child"><a href="/reports">List Laporan</a></li>
          <% if current_user.is_position(SALES) %>
            <li id="new-reports" class="sidebar-menu-child"><a href="/reports/new">Tambah Laporan</a></li>
          <% end%>
        </ul>
    </li>
    <% if(current_user.is_position(ADMINISTRATOR)) %>
      <li id="sidebar-menu-absens" class="sidebar-menu">
        <a href="<%=attendances_path%>">
          <i class="icon-book"></i>
          <span>Absensi</span>
        </a>
      </li>
      <li id="sidebar-menu-insentives" class="sidebar-menu">
        <a href="<%=insentives_path%>">
          <i class="icon-money"></i>
          <span>Insentive</span>
        </a>
      </li>
      <li id="sidebar-menu-customers" class="sidebar-menu">
        <a href="<%=customers_path%>">
          <i class="icon-group"></i>
          <span>Konsumen</span>
        </a>
      </li>
    <% end %>
    <% if(current_user.is_position(SUPERVISOR)) %>      
      <li id="sidebar-menu-insentives" class="sidebar-menu">
        <a href="<%=insentives_path%>">
          <i class="icon-money"></i>
          <span>Insentive</span>
        </a>
      </li>     
    <% end %>
  </ul>
</div>
<div id="hidden-pointer" style="display:none;">
  <div class="pointer">
    <div class="arrow"></div>
    <div class="arrow_border"></div>
  </div>
</div>
<!-- end sidebar -->