config/routes.rb
SalesManagementR4::Application.routes.draw do
  devise_for :users, controllers: {sessions: "sessions"}   

  root :to => redirect('/dashboard')
  match "/configurations" => "configurations/dashboard#index", via: [:get]

  resources :attendances do
    collection do
      get :get_list
    end
  end 
  resources :helps do
    collection do
    end
  end  

  resources :customers do
    collection do
      get :get_list
      get :filter_choosed_customer
      get :filter_position
    end
  end  

  resources :insentives do
    collection do
      get :get_list
      get :get_sales
      get :export
    end
  end  
  
  namespace :configurations do
    resources :users do
      collection do
        get :search
      end
    end  
    resources :dashboard
    resources :announcements
    resources :quotes do 
      collection do
        post :update_is_active
      end
    end 
    resources :news 
    resources :product_types do
      member do
        get :recover
      end
    end  

    resources :product_categories do
      member do
        get :recover
      end
    end  
    
    resources :report_prospects  do
      member do
        get :recover
      end
    end  

    resources :report_capacities do
      member do
        get :recover
      end
    end  

    resources :payment_types do
      member do
        get :recover
      end
    end  

    resources :office_hours   
  end
  resources :dashboard
  resources :reports do
    collection do
      get :get_customer
      get :filter_choosed
      get :filter_position
      post :set_color
    end
    member do
      get :writer
    end
  end

  resources :histories do
    collection do
    end
    member do
    end
  end

  
end

app/controllers/configurations/announcements_controller.rb
class Configurations::AnnouncementsController < Configurations::ConfigurationsController
  before_filter :authenticate_user!
  
  def index
  	@announcement = Announcement.last
  end
 
  def update
  	if params[:id] != "0"
	    if Announcement.find(params[:id]).update_attributes(:announcement => params[:value])
	      render :text => "true"
	    else
	    	render :text => "false"
	    end 
	  else
	    Announcement.create(:announcement => params[:value])
	  	render :text => "true"
	  end  	
  end 	
end

app/controllers/configurations/configurations_controller.rb
class Configurations::ConfigurationsController < ApplicationController

  protect_from_forgery
  before_filter :authenticate_user!, :is_admin?
  layout 'configurations'

  def require_admin_login
    # if current_user.nil? || !current_user.is_admin?
    #    flash[:error] = "Only admins are permitted"
    #    redirect_to log_in_path
    # else
    #    return current_user
    # end
  end

  def index
     render :layout => false
  end 	
end

app/controllers/configurations/dashboard_controller.rb
class Configurations::DashboardController < Configurations::ConfigurationsController
  layout 'configurations'
  
  def index;end
end

app/controllers/configurations/news_controller.rb
class Configurations::NewsController < Configurations::ConfigurationsController
	before_filter :authenticate_user!
  before_filter :find_news , :only => [:edit, :update, :destroy]

	def index
    @news = News.all.order('id ASC').paginate(:page =>(params[:page] || 1))
  end
  	
  def new
    @news = News.new
    @render_address = configurations_news_index_path
  end 

  def create
    @news = News.new(news_params)
    @render_address = configurations_news_index_path
    if @news.save(news_params)
      flash[:notice] = "Selamat, Anda berhasil menambah berita."
      redirect_to configurations_news_index_path 
    else
      flash[:notice] = "Maaf, Anda gagal menambah berita."
      p @news.errors.full_messages
      render :new
    end     
  end

  def edit
    @render_address = configurations_news_path
  end  

  def update    
    @render_address = configurations_news_path
    if @news.update_attributes(news_params)
      flash[:notice] = "Selamat, Anda berhasil mengupdate berita."
      redirect_to configurations_news_index_path
    else
      p @news.errors
      flash[:notice] = "Maaf, Anda gagal mengupdate berita."
      render :action =>  :edit
    end  
  end

  def destroy
    if @news.destroy          
      render :text => "true"
    else
      render :text => "false"
    end
  end  

  private  

  def news_params
    params.require(:news).permit(:title, :synopsis,:content, :news_image, :user_id, :expired_date)
  end 	

  def find_news
    @news = News.find(params[:id])
  end 
end

app/controllers/configurations/office_hours_controller.rb
class Configurations::OfficeHoursController < Configurations::ConfigurationsController
  before_filter :authenticate_user!
  before_filter :find_hour , :only => [:edit, :update, :destroy]

  def index
    @office_hours = OfficeHour.all.paginate(:page =>(params[:page] || 1))
  end
  	
  def new
    @office_hour = OfficeHour.new
    @office_hour.start_hour = Time.parse("00:00")
    @office_hour.end_hour = Time.parse("00:00")
    @render_address = configurations_office_hours_path
  end 

  def create
    @office_hour = OfficeHour.new(hour_params)
    @render_address = configurations_office_hours_path
    if @office_hour.save(hour_params)
      flash[:notice] = "Selamat, Anda berhasil menambah jam kerja."
      redirect_to configurations_office_hours_path 
    else
      flash[:notice] = "Maaf, Anda gagal menambah jam kerja."
      p @office_hour.errors
      render :new
    end     
  end

  def edit
    @render_address = configurations_office_hour_path
  end  

  def update    
    @render_address = configurations_office_hour_path
    if @office_hour.update_attributes(hour_params)
      flash[:notice] = "Selamat, Anda berhasil mengupdate jam kerja."
      redirect_to configurations_office_hours_path
    else
      p @office_hour.errors
      flash[:notice] = "Maaf, Anda gagal mengupdate jam kerja."
      render :action =>  :edit
    end  
  end

  def destroy
    if @office_hour.destroy          
      render :text => "true"
    else  
      render :text => "false"
    end
  end  

  private  

  def hour_params
    c = "#{params[:office_hour][:"start_hour(4i)"]}:#{ params[:office_hour][:"start_hour(5i)"]}"
    cto_date = c.to_time
    
    params[:office_hour][:start_hour] = cto_date #DateTime.strptime(cto_date,"%H:%M:%S")#c.strftime("%H:%M:00")
    
    c2 = "#{params[:office_hour][:"end_hour(4i)"]}:#{ params[:office_hour][:"end_hour(5i)"]}"
    params[:office_hour][:end_hour] = c2.to_time#DateTime.strptime(c2,"%H:%M:%S")#c.strftime("%H:%M:00")

    params.require(:office_hour).permit(:start_hour, :end_hour)
  end 	

  def find_hour
    @office_hour = OfficeHour.find(params[:id])
  end 
end

app/controllers/configurations/payment_types_controller.rb
class Configurations::PaymentTypesController < Configurations::ConfigurationsController
	before_filter :authenticate_user!
  before_filter :find_type , :only => [:edit, :update, :destroy]

	def index
    @payment_types = PaymentType.with_deleted.order('id ASC').order('deleted_at DESC').paginate(:page =>(params[:page] || 1))
  end
  	
  def new
    @payment_type = PaymentType.new
    @render_address = configurations_payment_types_path
  end 

  def create
    @payment_type = PaymentType.new(payment_params)
    if @payment_type.save(payment_params)
      flash[:notice] = "Selamat, Anda berhasil menambah cara pembayaran."
      redirect_to configurations_payment_types_path 
    else
      flash[:notice] = "Maaf, Anda gagal menambah cara pembayaran."
      p @payment_type.errors
      render :new
    end     
  end

  def show;end  

  def edit
    @render_address = configurations_payment_type_path
  end  

  def update    
    if @payment_type.update_attributes(payment_params)
      flash[:notice] = "Selamat, Anda berhasil mengupdate cara pembayaran."
      redirect_to configurations_payment_types_path
    else
      p @payment_type.errors
      flash[:notice] = "Maaf, Anda gagal mengupdate cara pembayaran."
      render :action =>  :edit
    end  
  end

  def update_is_active
    affectedRows =  PaymentType.update_all( "is_active = false", "id > 0" )
   
    payment_type = PaymentType.find(params[:id])    
    if payment_type.update_attributes(:is_active => true);
      render :text => "true"     
    else
      render :text => "false" 
    end
  end


  def destroy
    if @payment_type.destroy     
      flash[:notice] = "Selamat, Anda berhasil menghapus cara pembayaran."      
      render :text => "true"
    else
      flash[:error] = "Maaf, Anda gagal menghapus cara pembayaran."
      render :text => "false"
    end
  end  

  def recover
    record_to_recover = PaymentType.with_deleted.find(params["id"])
    if record_to_recover
      PaymentType.restore(params["id"])         
      render :text => "true"
    else
      render :text => "false"
    end
  end

  private  

  def find_type
    @payment_type = PaymentType.find(params[:id])
  end 

  def payment_params
    params.require(:payment_type).permit(:name)
  end	
    
end

app/controllers/configurations/product_categories_controller.rb
class Configurations::ProductCategoriesController < Configurations::ConfigurationsController
  before_filter :authenticate_user!
  before_filter :find_category , :only => [:edit, :update, :destroy]
  
  def index
    @categories = ProductCategory.with_deleted.order('id ASC').order('deleted_at DESC').paginate(:page =>(params[:page] || 1))
  end
  	
  def new
    @category = ProductCategory.new
    @render_address = configurations_product_categories_path
  end 

  def create
    @category = ProductCategory.new(category_params)
    @render_address = configurations_product_categories_path
    if @category.save(category_params)
      flash[:notice] = "Selamat, Anda berhasil menambah kategori."
      redirect_to configurations_product_categories_path 
    else
      flash[:notice] = "Maaf, Anda gagal menambah kategori."
      p @category.errors
      render :new
    end     
  end

  def edit
    @render_address = configurations_product_category_path
  end  

  def update    
    @render_address = configurations_product_category_path
    if @category.update_attributes(category_params)
      flash[:notice] = "Selamat, Anda berhasil mengupdate kategori."
      redirect_to configurations_product_categories_path
    else
      p @category.errors
      flash[:notice] = "Maaf, Anda gagal mengupdate kategori."
      render :action =>  :edit
    end  
  end

  def destroy
    if @category.destroy          
      render :text => "true"
    else
      render :text => "false"
    end
  end  

  def recover
    record_to_recover = ProductCategory.with_deleted.find(params["id"])
    if record_to_recover
      ProductCategory.restore(params["id"])         
      render :text => "true"
    else
      render :text => "false"
    end
  end

  private  

  def category_params
    params.require(:product_category).permit(:name)
  end 	

  def find_category
    @category = ProductCategory.find(params[:id])
  end 
end

app/controllers/configurations/product_types_controller.rb
class Configurations::ProductTypesController < Configurations::ConfigurationsController
before_filter :authenticate_user!
before_filter :find_product_type, :only => [:edit, :update, :destroy]

  def index
    @product_types = ProductType.with_deleted.order('id ASC').order('deleted_at DESC').paginate(:page =>(params[:page] || 1))
  end

  def new
    @product_type = ProductType.new
    @render_address = configurations_product_types_path
  end

  def create
    @product_type = ProductType.new(product_type_params)
    @render_address = configurations_product_types_path
    if @product_type.save(product_type_params)
      flash[:notice] = "Selamat, Anda berhasil menambah tipe kendaraan."
      redirect_to configurations_product_types_path 
    else
      flash[:notice] = "Maaf, Anda gagal menambah tipe kendaraan."
      p @product_type.errors
      render :new
    end     
  end

  def edit
    @render_address = configurations_product_type_path
  end  

  def update    
    @render_address = configurations_product_type_path
    if @product_type.update_attributes(product_type_params)
      flash[:notice] = "Selamat, Anda berhasil mengupdate tipe kendaraan."
      redirect_to configurations_product_types_path
    else
      p @product_type.errors
      flash[:notice] = "Maaf, Anda gagal mengupdate berita."
      render :action =>  :edit
    end  
  end

  def destroy
    if @product_type.destroy          
      render :text => "true"
    else
      render :text => "false"
    end
  end  

  def recover
    record_to_recover = ProductType.with_deleted.find(params["id"])
    if record_to_recover
      ProductType.restore(params["id"])         
      render :text => "true"
    else
      render :text => "false"
    end
  end


  private  

  def product_type_params
    params.require(:product_type).permit(:name)
  end 	

  def find_product_type
    @product_type = ProductType.find(params[:id])
  end 
  	
end

app/controllers/configurations/quotes_controller.rb
class Configurations::QuotesController < Configurations::ConfigurationsController
	before_filter :authenticate_user!
  before_filter :find_quote , :only => [:edit, :update, :destroy]

	def index
    @quotes = Quote.all.order('id ASC').paginate(:page =>(params[:page] || 1))
  end
  	
  def new
    @quote = Quote.new
    @render_address = configurations_quotes_path
  end 

  def create
    @quote = Quote.new(quote_params)
    if @quote.save(quote_params.merge(:is_active => 0))
      flash[:notice] = "Selamat, Anda berhasil menambah quote."
      redirect_to configurations_quotes_path 
    else
      flash[:notice] = "Maaf, Anda gagal menambah quote."
      p @quote.errors
      render :new
    end     
  end

  def show;end  

  def edit
    @render_address = configurations_quote_path
  end  

  def update    
    if @quote.update_attributes(quote_params)
      flash[:notice] = "Selamat, Anda berhasil mengupdate quote."
      redirect_to configurations_quotes_path
    else
      p @quote.errors
      flash[:notice] = "Maaf, Anda gagal mengupdate quote."
      render :action =>  :edit
    end  
  end

  def update_is_active
    affectedRows =  Quote.update_all( "is_active = false", "id > 0" )
   
    quote = Quote.find(params[:id])    
    if quote.update_attributes(:is_active => true);
      render :text => "true"     
    else
      render :text => "false" 
    end
  end


  def destroy
    if @quote.destroy     
      flash[:notice] = "Selamat, Anda berhasil menghapus quote."      
      render :text => "true"
    else
      flash[:error] = "Maaf, Anda gagal menghapus quote."
      render :text => "false"
    end
  end  

  private  

  def find_quote
    @quote = Quote.find(params[:id])
  end 

  def quote_params
    params.require(:quote).permit(:writer, :content).merge(:is_active=> 0)
  end	
    
end

app/controllers/configurations/report_capacities_controller.rb
class Configurations::ReportCapacitiesController < Configurations::ConfigurationsController
  before_filter :authenticate_user!
  before_filter :find_capacity , :only => [:edit, :update, :destroy]

  def index
    @capacities = ReportCapacity.with_deleted.order('id ASC').order('deleted_at DESC').paginate(:page =>(params[:page] || 1))
  end
  	
  def new
    @capacity = ReportCapacity.new
    @render_address = configurations_report_capacities_path
  end 

  def create
    @capacity = ReportCapacity.new(capacity_params)
    @render_address = configurations_report_capacities_path
    if @capacity.save(capacity_params)
      flash[:notice] = "Selamat, Anda berhasil menambah status kapasitas."
      redirect_to configurations_report_capacities_path 
    else
      flash[:notice] = "Maaf, Anda gagal menambah status kapasitas."
      p @capacity.errors
      render :new
    end     
  end

  def edit
    @render_address = configurations_report_capacity_path
  end  

  def update    
    @render_address = configurations_report_capacity_path
    if @capacity.update_attributes(capacity_params)
      flash[:notice] = "Selamat, Anda berhasil mengupdate status kapasitas."
      redirect_to configurations_report_capacities_path
    else
      p @capacity.errors
      flash[:notice] = "Maaf, Anda gagal mengupdate status kapasitas."
      render :action =>  :edit
    end  
  end

  def destroy
    if @capacity.destroy          
      render :text => "true"
    else
      render :text => "false"
    end
  end  

  def recover
    record_to_recover = ReportCapacity.with_deleted.find(params["id"])
    if record_to_recover
      ReportCapacity.restore(params["id"])         
      render :text => "true"
    else
      render :text => "false"
    end
  end

  private  

  def capacity_params
    params.require(:report_capacity).permit(:name)
  end 	

  def find_capacity
    @capacity = ReportCapacity.find(params[:id])
  end 
end

app/helpers/configurations/announcements_helper.rb
module Configurations::AnnouncementsHelper
end

app/helpers/configurations/colors_helper.rb
module Configurations::ColorsHelper
end

app/helpers/configurations/dashboard_helper.rb
module Configurations::DashboardHelper
end

app/helpers/configurations/news_helper.rb
module Configurations::NewsHelper
end

app/helpers/configurations/office_hours_helper.rb
module Configurations::OfficeHoursHelper
end

app/helpers/configurations/payment_types_helper.rb
module Configurations::PaymentTypesHelper
end

app/helpers/configurations/product_categories_helper.rb
module Configurations::ProductCategoriesHelper
end

app/views/configurations/users/_list.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th class="col-md-4 sortable">
        <span class="line"></span>Name
        
      </th>
      <th class="col-md-3 sortable">
        <span class="line"></span>Username
      </th>
      <th class="col-md-3 sortable">
        <span class="line"></span>Signed up
      </th>
      <th class="col-md-2 sortable">
        <span class="line"></span>Position
      </th>
      <th class="col-md-2 sortable">
        <span class="line"></span>Responsible
      </th>
      <th class="col-md-3 sortable">
        <span class="line"></span>Email
      </th>
      <th class="col-md-2 sortable">
        <span class="line"></span>Action
      </th>
    </tr>
  </thead>
  <div id="">
    <tbody>
      <%users.each do |user|%>
        <tr>
          <td><%= image_tag user.try(:profile_picture).url(:thumb), :class=>"profile-picture", :style => "width:32px;margin-right:10px;"%>
            <%if user.try(:deleted_at).nil?%>
              <%= link_to user.try(:name) , edit_configurations_user_path(user)%>
            <%else%>
              <%= user.try(:name)%>
            <%end%>
          </td>
          <td><%= user.try(:username)%></td>
          <td><%= user.try(:created_at).strftime("%d/%m/%Y")%></td>
          <td><%= user.try(:get_position) %></td>
          <td><%= user.try(:parent).name rescue nil%></td>
          <td><%= user.try(:email) rescue "-"%></td>
          <td>
            <%if user.try(:deleted_at).nil?%>
              <%= button_to "Hapus", configurations_user_path(user), :data => { :confirm => "Apakah Anda Yakin?"} , :method => :delete, :class=>"btn btn-primary" %>
            <%else%>
              Deleted
            <%end%>
          </td>
        <tr></tr>
      <%end unless @users.blank?%>
    </tbody>
  </div>  
</table>

app/views/configurations/users/edit.html.erb
<% content_for :title do %>
  Edit Karyawan - Configurations
<% end %>
<!-- main container .wide-content is used for this layout without sidebar :)  -->
  <div class="content">
    <div class="settings-wrapper" id="pad-wrapper">
      <div class="row">           
        <%= form_for(@user, :url => configurations_user_path, :method=> :put, :html => { :class=> 'form-horizontal', :id=>"myform",multipart: true  }) do |f| %>
        <%= csrf_meta_tags %>  
        <!-- avatar column -->
        <div class="col-md-3 col-md-offset-1 avatar-box" style="width:354px;">
          <div class="personal-image">
            <%= image_tag @user.profile_picture.url(:medium), :class=>"profile-picture"%>
            <p>Upload a different photo...</p>         
            <%= f.file_field :profile_picture  %>
          </div>
        </div>

        <!-- edit form column -->
        <div class="col-md-7 personal-info">
          <h5 class="personal-title">Personal info</h5> 
            <% if @user.errors.any? %>
              <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            <%end%>
            <div class="form-group">
              <label class="col-lg-2 control-label">Name:</label>
              <div class="col-lg-8">                   
                <%= f.text_field :name , :class=> 'form-control', :placeholder=> 'Nama Karyawan', tabindex: '1',:required => "required"%>
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-2 control-label">Username:</label>
              <div class="col-lg-8">                   
                <%= f.text_field :username , :class=> 'form-control', :placeholder=> 'Username', tabindex: '1',:required => "required"%>
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-2 control-label">Email:</label>
              <div class="col-lg-8">
                 <%= f.text_field :email , :class=> 'form-control', :placeholder=> 'Email', tabindex: '1',:required => "required"%>               
              </div>
            </div>           
           
            <div class="form-group">
              <label class="col-lg-2 control-label">Password:</label>
              <div class="col-lg-8">  
                
                 <%= f.password_field :password, :autocomplete => "off", tabindex: '1',:class=> 'pwd', :style => "width:80%" ,:value => @user.password%>
                 <br>   
                 <i>(just leave this blank if you don't want to change your current password)</i></p>                    
              </div>
            </div>
          
            <div class="form-group">
              <label class="col-lg-2 control-label">Gender:</label>
              <div class="col-lg-8">
                 <%= f.select :sex, options_for_select(@gender, (@user.sex == true ? 1 : 0 ) ),:required => "required"%>                
              </div>
            </div>
            
            <div class="form-group">
              <label class="col-lg-2 control-label">Position:</label>
              <div class="col-lg-8">
                 <%= f.select :position, options_for_select(@position, @user.position), :prompt => "Jabatan",:required => "required"%>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label">Address:</label>
              <div class="col-lg-8">
                 <%= f.text_field :address , :class=> 'form-control', :placeholder=> 'Address', tabindex: '1',:required => "required"%>          
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-2 control-label">City:</label>
              <div class="col-lg-8">
                <%= f.text_field :city , :class=> 'form-control', :placeholder=> 'City', tabindex: '1',:required => "required"%>                
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-2 control-label">Phone Number:</label>
              <div class="col-lg-8">
                 <%= f.text_field :phone_number , :class=> 'form-control', :placeholder=> 'Phone Number', tabindex: '1',:required => "required"%>                 
              </div>
            </div>
            <div class="actions">
              <%= f.submit :save_changes , :value=> "Save Changes", :class => 'btn btn-primary'%>
              <span>OR</span>
              <%= link_to "Cancel", configurations_users_path%>
              
            </div>
          
        </div>
      </div>  

      <%end%>
    </div>
  </div>
  <!-- end main container -->
 

app/views/configurations/users/new.html.erb
<!-- main container .wide-content is used for this layout without sidebar :)  -->
  <div class="content">
    <div class="settings-wrapper" id="pad-wrapper">
      <div class="row">           
        <%= form_for(@user, :url => configurations_users_path, :html => { :class=> 'form-horizontal', :id=>"myform",multipart: true  }) do |f| %>
        <%= csrf_meta_tags %>  
        
        <!-- avatar column -->
        <div class="col-md-3 col-md-offset-1 avatar-box">
          <div class="personal-image">
            <img src="/assets/personal-info.png" class="avatar img-circle">
            <p>Upload a different photo...</p>         
            <%= f.file_field :profile_picture ,:required => "required" %>
          </div>
        </div>

        <!-- edit form column -->
        <div class="col-md-7 personal-info">
          <h5 class="personal-title">Personal info</h5> 
            <div class="form-group"> 
              <% if @user.errors.any? %>
                <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
              <%end%>
            </div>
            <div class="form-group">
              <label class="col-lg-2 control-label">Name:</label>
              <div class="col-lg-8">                   
                <%= f.text_field :name , :class=> 'form-control', :placeholder=> 'Nama Karyawan', tabindex: '1',:required => "required"%>
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-2 control-label">Username:</label>
              <div class="col-lg-8">                   
                <%= f.text_field :username , :class=> 'form-control', :placeholder=> 'Username', tabindex: '1',:required => "required"%>
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-2 control-label">Email:</label>
              <div class="col-lg-8">
                 <%= f.text_field :email , :class=> 'form-control', :placeholder=> 'Email', tabindex: '1',:required => "required"%>               
              </div>
            </div>           
           
            <div class="form-group">
              <label class="col-lg-2 control-label">Password:</label>
              <div class="col-lg-8">  
                 <%= f.password_field :password, :autocomplete => "off", tabindex: '1',:class=> 'pwd', :style => "width:80%" ,:required => "required"%>                       
              </div>
            </div>
          
            <div class="form-group">
              <label class="col-lg-2 control-label">Gender:</label>
              <div class="col-lg-8">
                 <%= f.select :sex, options_for_select(@gender, 1), :prompt => "Jenis Kelamin",:required => "required"%>
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-2 control-label">Position:</label>
              <div class="col-lg-8">
                 <%= f.select :position, options_for_select(@position, 1), :prompt => "Jabatan",:required => "required"%>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label">Address:</label>
              <div class="col-lg-8">
                 <%= f.text_field :address , :class=> 'form-control', :placeholder=> 'Address', tabindex: '1',:required => "required"%>          
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-2 control-label">City:</label>
              <div class="col-lg-8">
                <%= f.text_field :city , :class=> 'form-control', :placeholder=> 'City', tabindex: '1',:required => "required"%>                
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-2 control-label">Phone Number:</label>
              <div class="col-lg-8">
                 <%= f.text_field :phone_number , :class=> 'form-control', :placeholder=> 'Phone Number', tabindex: '1',:required => "required"%>                 
              </div>
            </div>
            <div class="actions">
              <%= f.submit :save_changes , :value=> "Save Changes", :class => 'btn btn-primary'%>
              <span>OR</span>
              <%= link_to "Cancel", configurations_users_path%>
              
            </div>
          
        </div>
      </div>  

      <%end%>
    </div>
  </div>
  <!-- end main container -->

app/views/configurations/users/show.html.erb
<!-- main container .wide-content is used for this layout without sidebar :)  -->
  <div class="content">
    <div class="settings-wrapper" id="pad-wrapper">
      <div class="row">           
        <%= form_for(@user, :url => configurations_users_path, :html => { :class=> 'form-horizontal', :id=>"myform",multipart: true  }) do |f| %>
        <%= csrf_meta_tags %>  
        <!-- avatar column -->
        <div class="col-md-3 col-md-offset-1 avatar-box">
          <div class="personal-image">            
            <%= image_tag @user.profile_picture.url(:medium), :class=>"profile-picture"%>
          </div>
        </div>

        <!-- edit form column -->
        <div class="col-md-7 personal-info">
          <h5 class="personal-title">Personal info</h5>          
            <div class="form-group">
              <label class="col-lg-2 control-label">Username:</label>
              <div class="col-lg-8">          
                <%= @user.username%>       
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-2 control-label">Email:</label>
              <div class="col-lg-8">
                 <%= f.text_field :email , :class=> 'form-control', :placeholder=> 'Email', tabindex: '1',:required => "required"%>               
              </div>
            </div>           
      
          
            <div class="form-group">
              <label class="col-lg-2 control-label">Gender:</label>
              <div class="col-lg-8">
                <%=@user.sex? ? "Pria" : "Wanita"%>
                 <%#= f.select :sex, options_for_select(@gender, 1), :prompt => "Jenis Kelamin",:required => "required"%>                
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-2 control-label">Address:</label>
              <div class="col-lg-8">
                 <%= f.text_field :address , :class=> 'form-control', :placeholder=> 'Address', tabindex: '1',:required => "required"%>          
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-2 control-label">City:</label>
              <div class="col-lg-8">
                <%= f.text_field :city , :class=> 'form-control', :placeholder=> 'City', tabindex: '1',:required => "required"%>                
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-2 control-label">Phone Number:</label>
              <div class="col-lg-8">
                 <%= f.text_field :phone_number , :class=> 'form-control', :placeholder=> 'Phone Number', tabindex: '1',:required => "required"%>                 
              </div>
            </div>
            <div class="actions">
              <%= f.submit :save_changes , :value=> "Save Changes", :class => 'btn btn-primary'%>
              <span>OR</span>
              <%= link_to "Cancel", configurations_users_path%>
              
            </div>
          
        </div>
      </div>  

      <%end%>
    </div>
  </div>
  <!-- end main container -->