config/routes.rb
SalesManagementR4::Application.routes.draw do
  devise_for :users, controllers: {sessions: "sessions"}   

  root :to => redirect('/dashboard')
  match "/configurations" => "configurations/dashboard#index", via: [:get]

  resources :attendances do
    collection do
      get :get_list
    end
  end 
  resources :helps do
    collection do
    end
  end  

  resources :customers do
    collection do
      get :get_list
      get :filter_choosed_customer
      get :filter_position
    end
  end  

  resources :insentives do
    collection do
      get :get_list
      get :get_sales
      get :export
    end
  end  
  
  namespace :configurations do
    resources :users do
      collection do
        get :search
      end
    end  
    resources :dashboard
    resources :announcements
    resources :quotes do 
      collection do
        post :update_is_active
      end
    end 
    resources :news 
    resources :product_types do
      member do
        get :recover
      end
    end  

    resources :product_categories do
      member do
        get :recover
      end
    end  
    
    resources :report_prospects  do
      member do
        get :recover
      end
    end  

    resources :report_capacities do
      member do
        get :recover
      end
    end  

    resources :payment_types do
      member do
        get :recover
      end
    end  

    resources :office_hours   
  end
  resources :dashboard
  resources :reports do
    collection do
      get :get_customer
      get :filter_choosed
      get :filter_position
      post :set_color
    end
    member do
      get :writer
    end
  end

  resources :histories do
    collection do
    end
    member do
    end
  end

  
end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :report
  belongs_to :user

  def self.per_period
    self.where("DATE(created_at) BETWEEN '#{Report.startdate_period}' AND '#{Report.enddate_period}'")
  end

  def self.filtered(params, current_user)
    reports = Report.filtered(params,current_user)
    arr_ids = reports.pluck(:id)
    arr_ids = arr_ids.join(", ")
    histories = History.where("report_id in (#{arr_ids})")
    histories.count
  end

end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController

  def show
    @histories = History.where(:report_id => params[:id]).paginate(:page =>(params[:page] || 1)).per_page(20)
    @parent_report = Report.find(params[:id])
  end

end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_table.html.erb
<div class="row" style="overflow:scroll;">
  <div style="width:4000px;">
    <table class="report-table">
      <thead>
        <tr>
          <th>Dibuat</th>
          <th>Diperbaharui</th>
          <th>Diperbaharui oleh</th>

          <th>Nama Perusahaan</th>
          <th>Nama Konsumen</th>
          <th>Alamat</th>
          <th>Jenis Kelamin</th>
          <th>Tanggal Lahir</th>
          <th>No. Telp 1</th>
          <th>No. Telp 2</th>
          <th>No. Telp 3</th>
          <th>Kelurahan</th>
          <th>Kecamatan</th>
          <th>Wilayah</th>
          <th>Kota</th>
          <th>Agama</th>

          <th>No STNK</th>
          <th>Nama STNK</th>
          <th>Warna Plat</th>
          <th>Warna</th>
          <th>Jenis</th>
          <th>Tipe</th>
          <th>Tahun</th>
          <th>Kapasitas</th>
          <th>No Mesin</th>
          <th>No Rangka</th>

          <th>Status Kapasitas</th>
          <th>Status Prospek</th>
          <th>Uang Tanda Jadi</th>
          <th>Harga Jual</th>
          <th>Bank</th>
          <th>Cara Pembayaran</th>
          <th>Sektor Bisnis</th>
          <th style="max-width:100px;">Keterangan</th>

        </tr>
      </thead>
      <tbody>
        <!-- row -->
        <% if @histories.present? %>
          <% @histories.each do |history| %>
            <% report = JSON.parse(history.changes_report) rescue nil %>
            <% if report.present? %>
              <% customer = report["customer"] %>
              <% product = report["product"] %>
              <%if report["report"]["color"].present? %>
                <tr class="colorize-row" style="background-color:<%=report["report"]["color"]%>;">
              <% else %>
                <tr>
              <% end %>

                <% if current_user.is_position(SALES) %>
                  <td><%=link_to(((report["report"]["created_at"].to_datetime).strftime("%d %b %Y %H:%M:%S") rescue nil),edit_report_path(report["report"]["id"])) rescue nil %></td>
                <% else %>
                  <td><%=link_to(((report["report"]["created_at"].to_datetime).strftime("%d %b %Y %H:%M:%S") rescue nil),report_path(report["report"]["id"])) rescue nil %></td>
                <% end %>
                <td><%=report["report"]["created_at"] != report["report"]["updated_at"] ? (report["report"]["updated_at"].to_datetime).strftime("%d %b %Y %H:%M:%S") : "-" %></td>
                <td><%=history.user.name rescue "-" %></td>

                <td><%= customer["company_name"] rescue "-" %></td>
                <td><%= customer["name"] rescue "-" %></td>
                <td><%= customer["address"] rescue "-" %></td>
                <td><%= (customer["sex"] ? 'Pria' : 'Wanita') rescue "-" %></td>
                <td><%= customer["date_of_birth"] %></td>
                <td><%= customer["phone_number"] rescue nil %></td>
                <td><%= customer["handphone_number"] rescue nil %></td>
                <td><%= customer["other_phone_number"] rescue nil %></td>
                <td><%= customer["sub_district"] rescue "-" %></td>
                <td><%= customer["village"] rescue "-" %></td>
                <td><%= customer["district"] rescue "-" %></td>
                <td><%= customer["city"] rescue "-" %></td>
                <td><%= customer["string_religion"] %></td>

                <td><%= product["license_number"] rescue "-" %></td>
                <td><%= product["license_name"] rescue "-" %></td>
                <td><%= product["string_license_color"] rescue "-" %></td>
                <td><%= product["color"] rescue "-" %></td>
                <td><%= ProductCategory.find(product["product_category_id"]).name rescue "-" %></td>
                <td><%= ProductType.find(product["product_type_id"]).name rescue "-" %></td>
                <td><%= product["manufactured_year"] rescue "-" %></td>
                <td><%= product["engine_capacity"] rescue "-" %></td>
                <td><%= product["engine_number"] rescue "-" %></td>
                <td><%= product["chassis_number"] rescue "-" %></td>
                
                <td><%=ReportCapacity.find(report["report"]["report_capacity_id"]).name rescue nil %></td>
                <td><%=ReportProspect.find(report["report"]["report_prospect_id"]).name rescue nil %></td>
                <td><%=report["report"]["advance"]%></td>
                <td><%=report["report"]["selling_price"]%></td>
                <td><%=Bank.find(report["report"]["bank_id"]).full_name rescue "" %></td>
                <td><%=PaymentType.find(report["report"]["payment_type_id"]).name rescue "" %></td>
                <td><%=report["report"]["business_sector"] rescue "-" %></td>
                <td><a href="javascript:void(0)" title="<%=report['notes']%>" ><%=truncate(report["notes"], length: 160, omission: '...')%></a></td>
              </tr>
            <% end %>
          <% end %>
        <% else %>
          <tr>
            <td colspan="32">
              No Data Found
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>  
  </div>
</div>
<div class="digg_pagination pagination pull-right">          
  <%= will_paginate @histories, :container => false, renderer: BootstrapPagination::Rails %>
</div>

app/views/histories/show.html.erb
<% content_for :title do %>
  History 
<% end %>

<% content_for :specific_style do %>
  <link rel="stylesheet" data-turbolinks-track href="/assets/compiled/index.css" type="text/css" media="screen" />
  <link href="/assets/lib/morris.css" data-turbolinks-track type="text/css" rel="stylesheet" />
<% end %>

<!-- main container -->
<div class="content">

  <div id="pad-wrapper" style="margin-top:0px;"> 

    <% if @histories.present? %>
      <!-- morris bar & donut charts -->

      <div class="table-products " style="margin-top:30px;">
        <div class="row head" style="margin-bottom:10px;">
          <!-- <div class="col-md-1">
            <%=link_to "Back", report_path(@parent_report.id), {class: "btn-flat success"}%>
          </div> -->
          <div class="col-md-11">
            <h4>History Laporan <%=@parent_report.user.name %> tanggal <%= @parent_report.created_at.strftime("%d %B %Y") %></h4>
          </div>
        </div>

        <%= render :partial=> 'table'%>
      </div>
    <% else %>
      <h5>No Data</h5>
    <% end %>
  </div>
</div>