config/routes.rb
SalesManagementR4::Application.routes.draw do
  devise_for :users, controllers: {sessions: "sessions"}   

  root :to => redirect('/dashboard')
  match "/configurations" => "configurations/dashboard#index", via: [:get]

  resources :attendances do
    collection do
      get :get_list
    end
  end 
  resources :helps do
    collection do
    end
  end  

  resources :customers do
    collection do
      get :get_list
      get :filter_choosed_customer
      get :filter_position
    end
  end  

  resources :insentives do
    collection do
      get :get_list
      get :get_sales
      get :export
    end
  end  
  
  namespace :configurations do
    resources :users do
      collection do
        get :search
      end
    end  
    resources :dashboard
    resources :announcements
    resources :quotes do 
      collection do
        post :update_is_active
      end
    end 
    resources :news 
    resources :product_types do
      member do
        get :recover
      end
    end  

    resources :product_categories do
      member do
        get :recover
      end
    end  
    
    resources :report_prospects  do
      member do
        get :recover
      end
    end  

    resources :report_capacities do
      member do
        get :recover
      end
    end  

    resources :payment_types do
      member do
        get :recover
      end
    end  

    resources :office_hours   
  end
  resources :dashboard
  resources :reports do
    collection do
      get :get_customer
      get :filter_choosed
      get :filter_position
      post :set_color
    end
    member do
      get :writer
    end
  end

  resources :histories do
    collection do
    end
    member do
    end
  end

  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_all_data_for_combobox
  before_filter :titleize_customer, :only=>[:create,:update]
  before_filter :customer_params, :only=>[:create,:update]
  before_filter :product_params, :only=>[:create,:update]
  before_filter :report_params, :only=>[:create,:update]

  def index
    @perpage = 25
    @call = 0
    @report_prospects = ReportProspect.all
    @branch_managers = User.where("position = #{HEAD_BRANCH}").order("name ASC").map { |e| [e.name,e.id] }
    @workday = (Date.today - Report.startdate_period.to_date).to_i
    if params[:filter].present?
      @call = History.filtered(params,current_user)
      @all_reports = Report.filtered(params,current_user)
      @reports = @all_reports.paginate(:page =>(params[:page] || 1)).per_page(@perpage)
      @workday = ((params['filter']['to'].to_date rescue Date.today) - params['filter']['from'].to_date).to_i
    else
      if current_user.is_position(ADMINISTRATOR)
        @all_reports = Report.per_period
      elsif current_user.is_position(VISITOR)
        @all_reports = Report.per_period
      elsif current_user.is_position(HEAD_BRANCH)
        @all_reports = Report.per_period.where("user_id IN (
                                  SELECT sales.id 
                                  FROM users sales 
                                  WHERE sales.parent_id IN (
                                    SELECT supervisor.id 
                                    FROM users supervisor 
                                    WHERE supervisor.parent_id = #{current_user.id}
                                  ) 
                    )")
      elsif current_user.is_position(SUPERVISOR)
        @all_reports = Report.per_period.where("user_id IN (SELECT id FROM users WHERE parent_id=#{current_user.id})")
      elsif current_user.is_position(SALES)
        @all_reports = Report.per_period.where("user_id = #{current_user.id}")
      end
      @reports = @all_reports.paginate(:page =>(params[:page] || 1)).per_page(35)
    end
  end

  def new
    return redirect_to reports_path if !current_user.is_position(SALES)
    @target = ""
  end

  def show
    @target = "show"
    @report = Report.find(params[:id])
    @customer = @report.customer
    @vehicle = @report.product
  end

  def writer
    @user = User.find(params[:id])
  end

  def edit
    @target = params[:id]
    @report = Report.find(params[:id])
    @customer = @report.customer if params[:customer].blank?
    @vehicle = @report.product if params[:product].blank?
  end

  def create
    @target = ""
    if params[:customer_id].present?
      customer = Customer.find(params[:customer_id])
      customer.update_attributes(customer_params.merge({:user_id => current_user.id}))
    else
      customer = Customer.new(customer_params.merge({:user_id => current_user.id}))
    end
    vehicle = Product.new(product_params)
    report = Report.new(report_params)
    @customer = customer
    @vehicle = vehicle
    @report = report
    Report.transaction do
      if !customer.save
        @customer = customer
        flash[:error] = "Maaf, Terjadi kegagalan penyimpanan data Konsumen"
        return render :new
      end
      if !vehicle.save
        @vehicle = vehicle
        flash[:error] = "Maaf, Terjadi kegagalan penyimpanan data Kendaraan"
        return render :new
      end
      report = Report.new(report_params.merge({:user_id => current_user.id,:customer_id => customer.id, :product_id => vehicle.id, :updated_by => current_user.id}))
      if !report.save
        @report = report
        flash[:error] = "Maaf, Terjadi kegagalan penyimpanan data Laporan"
        return render :new
      end
        flash[:success] = "Laporan berhasil dibuat"
        redirect_to reports_path

    end
  end

  def update
    @customer = Customer.new(customer_params.merge({:user_id => current_user.id}))
    @vehicle = Product.new(product_params)
    @report = Report.new(report_params)
    @target = params[:id]
    customer = Customer.find(params[:customer_id])
    vehicle = Product.find(params[:vehicle_id])
    report = Report.find(params[:id])

    if params[:customer][:village].blank?
        flash[:error] = "Maaf, Kecamatan harus diisi"
        return redirect_to edit_report_path(params[:id])
    end

    if params[:vehicle][:manufactured_year].blank?
        flash[:error] = "Maaf, Tahun produksi harus diisi"
        return redirect_to edit_report_path(params[:id])
    end

    if params[:report][:payment_type_id].blank?
        flash[:error] = "Maaf, Cara pembayaran harus diisi"
        return redirect_to edit_report_path(params[:id])
    end

    if params[:report][:selling_price].blank?
        flash[:error] = "Maaf, Harga Jual harus diisi"
        return redirect_to edit_report_path(params[:id])
    end

    if ReportProspect.find(params[:report][:report_prospect_id]).name=='SPK'
      if @report.advance.blank?
        flash[:error] = "Maaf, Tanda Jadi harus diisi bila SPK"
        return redirect_to edit_report_path(params[:id])
      end
    end
    if ReportProspect.find(params[:report][:report_prospect_id]).is_final
      result = validate_all_form(params)
      if result=="customer-false"
        flash[:error] = "Maaf, Data Konsumen anda belum terisi semua. Silahkan isi semua"
      elsif result=="vehicle-false"
        flash[:error] = "Maaf, Data Kendaraan anda belum terisi semua. Silahkan isi semua"
      elsif result=="report-false"
        flash[:error] = "Maaf, Data Laporan anda belum terisi semua. Silahkan isi semua"
      end
      if result!="true"
        return redirect_to edit_report_path(params[:id])
      end
    end
    if current_user.id != report.user_id
      flash[:error] = "Maaf, Anda tidak memiliki hak akses untuk merubah data"
      return redirect_to edit_report_path(params[:id])
    end
    status = false
    Report.transaction do
      if customer.update_attributes(customer_params.merge({:user_id => current_user.id}))
        report.touch
      end
      if vehicle.update_attributes(product_params)
        report.touch
      end
      if report.update_attributes(report_params.merge({:updated_by => current_user.id}))
        status = true
      end
    end

    if status
      flash[:success] = "Laporan berhasil diperbaharui"
    else
      flash[:error] = "Maaf, Terjadi kesalahan penyimpanan Laporan"
    end
    return redirect_to edit_report_path(params[:id])

  end

  def destroy
    
  end

  def filter_choosed
    @option = params[:option]
    @option_select = []
    @option_choosed = params[:option_choosed]
    case params[:selected]
      when "religion_id"
        @option_select = RELIGIONS
      when "report_capacity_id"
        @option_select = ReportCapacity.order("name ASC").map { |e| [e.name,e.id] }
      when "report_prospect_id"
        @option_select = ReportProspect.order("name ASC").map { |e| [e.name,e.id] }
      when "bank_id"
        @option_select = Bank.order("full_name ASC").map { |e| [e.full_name,e.id] }
      when "license_color_id"
        @option_select = LICENSE_COLOR
      when "product_category_id"
        @option_select = ProductCategory.order("name ASC").map { |e| [e.name,e.id] }
      when "product_type_id"
        @option_select = ProductType.order("name ASC").map { |e| [e.name,e.id] }
      # additional
      when "user_name"
        @option_select = User.where("position = #{SALES}").order("name ASC").map { |e| [e.name,e.id] }
      when "sex"
        @option_select = [["Pria",1],["Wanita",0]]
      when "payment_type_id"
        @option_select = PaymentType.order("name ASC").map { |e| [e.name,e.id] }
    end
    respond_to do |format|
      format.js
    end
  end

  def get_customer
    customers = Customer.where("user_id = #{current_user.id} AND name LIKE '%#{params[:keyword]}%'").limit(params[:max_rows])
    render :json => {:customers => customers}
  end

  def filter_position
    @type = params[:type]
    @option_select = []
    @option_choosed = params[:selected]
    case params["type"]
      when "branch_manager"
        @option_select = User.where("position = '#{SUPERVISOR}' AND parent_id = #{params[:filter_id]}").order("name ASC").map { |e| [e.name, e.id] }
      when "supervisor"
        @option_select = User.where("position = '#{SALES}' AND parent_id = #{params[:filter_id]}").order("name ASC").map { |e| [e.name, e.id] }
      
    end if params[:filter_id].present?
    respond_to do |format|
      format.js
    end
  end

  def set_color
    report  = Report.find(params["id"])
    if report.update_attributes({color: params["color"],business_sector: " - ",updated_by: current_user.id})
      return render json: ({result: "success"})
    else
      return render json: ({result: report.errors})
    end
  end

  private
    def get_all_data_for_combobox
      @product_category = ProductCategory.order("name ASC")
      @product_type = ProductType.order("name ASC")
      @banks = Bank.order("full_name ASC")
      @payment_type = PaymentType.order("name ASC")
      @report_prospect = ReportProspect.order("name ASC")
      @report_capacity = ReportCapacity.order("name ASC")
      @payment_type = PaymentType.order("name ASC")
    end

    def validate_all_form(params)
      # validate customer
      params[:customer].each do |key,customer|
        return "customer-false" if customer.blank?
      end

      status = true
      params[:vehicle].each do |key,vehicle|
        return "vehicle-false" if vehicle.blank?
      end

      status = true
      params[:report].each do |key,report|
        return "report-false" if report.blank?
      end
      return "true"
      # c = params[:customer]

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<div class="content">
<%= csrf_meta_tag %>
  <!-- settings changer -->
  <div id="pad-wrapper" class="form-page">
    <% if (@target != "show") %>
      <%= form_tag("#{@target=='' ? reports_path : report_path(@target) }", method: "#{@target=='' ? 'POST' : 'PUT' }") do -%>
        <div class="row form-header" style="border-bottom:1px solid #DEDEDE;margin-bottom:30px;">
          <div class="col-md-12 column">
            <h3 class="tab-report left">
              <a href="#customer" form="customer" class="tab-link selected tab-customer"> KONSUMEN </a>
              <a href="#vehicle" form="vehicle" class="tab-link tab-vehicle"> KENDARAAN </a>
              <a href="#report" form="report" class="tab-link tab-report"> LAPORAN </a>
            </h3>
            <button style="display: inline-block;" type="submit" class="btn btn-success btn-next right" data-last="Finish">
              <%= @target == params[:id] ? 'Perbaharui' : 'Simpan' %> <i class="icon-chevron-right"></i>
            </button>
            <div class="clear"></div>
          </div>
        </div>
        <div class="form-master">
          <%= render :partial=> 'form_customer'%>
          <%= render :partial=> 'form_vehicle'%>
          <%= render :partial=> 'form_report'%>
        </div>
      <% end -%>
    <% else %>      
      <%= form_tag('#') do -%>
        <div class="row form-header" style="border-bottom:1px solid #DEDEDE;margin-bottom:30px;">
          <div class="col-md-12 column">
            <h3 class="tab-report left">
              <a href="#customer" form="customer" class="tab-link selected tab-customer"> KONSUMEN </a>
              <a href="#vehicle" form="vehicle" class="tab-link tab-vehicle"> KENDARAAN </a>
              <a href="#report" form="report" class="tab-link tab-report"> LAPORAN </a>
            </h3>
            <div class="clear"></div>
          </div>
        </div>
        <div class="form-master">
          <%= render :partial=> 'form_customer'%>
          <%= render :partial=> 'form_vehicle'%>
          <%= render :partial=> 'form_report'%>
        </div>
      <% end -%>
    <% end %>      
  </div>
</div>
<% content_for :style do %>
  <style type="text/css">

    .ui-autocomplete-loading {
      background: white url('images/ui-anim_basic_16x16.gif') right center no-repeat;
    }

    .ui-menu{
      width: 300px;
    }

    #find-customer { width: 25em; }

    .form-page .form-wrapper .field-box{
      margin-bottom: 10px;
    }
    .radio{
      margin-top: 0px;
      margin-bottom: 0px;
    }
    .radio input{
      margin-right: 5px;
    }

    .tab-report{
      height: 45px;
    }

    .tab-report a{
      text-decoration: none;
      color: #CCC;
      transition: 0.5s;
    }

    .tab-report a.selected{
      text-decoration: none;
      font-size: xx-large;
      color: #057BDA;
      transition: 0.5s;
    }
  </style>
<% end %>
<% content_for :script do %>
  <script type="text/javascript">
    $(function() {

      <% if @target=="show" %>
        $("form input").each(function(){
          $(this).attr("readonly",true)
          $(this).attr("placeholder",null)
          $(this).attr("disabled","disabled")
        })
        $("form textarea").each(function(){
          $(this).attr("readonly",true)
          $(this).attr("placeholder",null)
          $(this).attr("disabled","disabled")
        })
        $("form select").each(function(){
          $(this).attr("disabled","disabled")
        })
      <% end %>
      recalculateTab()

      <% if (@report.errors.present? rescue false)%>
        $(".tab-report").trigger("click")
      <% end %>

      <% if (@vehicle.errors.present? rescue false)%>
        $(".tab-vehicle").trigger("click")
      <% end %>

      <% if (@customer.errors.present? rescue false)%>
        $(".tab-customer").trigger("click")
      <% end %>
    
    });

    function recalculateTab(){
      $(".tab-customer").trigger("click")
      $(".tab-link").click(function(){
        $(".tab-link").each(function(index, el) {
          $(el).removeClass("selected");
          $(".form-"+$(el).attr('form')).slideUp(500);
        });
        $(this).addClass("selected");
        $(".form-"+$(this).attr('form')).slideDown(500);
      })
      if (window.location.hash !=""){
        $(".tab-link").each(function(index, el) {
          $(el).removeClass("selected");
          if (window.location.hash == $(el).attr('href')){
            $(el).trigger('click');
            $(".form-"+$(el).attr('form')).show();
          }
        });
      }else{
        $(".tab-customer").trigger("click")
      }
    }

    $(function() {
      function log( message ) {
        $( "<div>" ).text( message ).prependTo( "#log" );
        $( "#log" ).scrollTop( 0 );
      }
      $( "#find-customer" ).autocomplete({
        source: function( request, response ) {
          $.ajax({
            url: "<%=get_customer_reports_path%>",
            data: {
            max_row: 15,
            keyword: request.term
          },
            success: function( data ) {
              response( $.map( data.customers, function( item ) {
                return {
                  customer: item,
                  label: item.name,
                  value: item.name
                }
              }));
            }
          });
        },
        select: function( event, ui ) {
          customer = ui.item.customer
          log( ui.item ?
          "Selected: " + ui.item.customer.name :
          "Nothing selected, input was " + this.customer.name);

          $("#customer_id").val(customer.id);
          $("#customer_company_name").val(customer.company_name);
          $("#customer_name").val(customer.name);
          $("#customer_address").val(customer.address);
          $("#customer_date_of_birth").val(customer.date_of_birth);
          $("#customer_sub_district").val(customer.sub_district);
          $("#customer_village").val(customer.village);
          $("#customer_district").val(customer.district);
          $("#customer_city").val(customer.city);
          console.log(customer.sex)
          if(customer.sex){
            $("#customer_sex_1").prop("checked", true)
            $("#customer_sex_2").prop("checked", false)
          }else{
            $("#customer_sex_1").prop("checked", false)
            $("#customer_sex_2").prop("checked", true)
          }
          $("#customer_phone_number").val(customer.phone_number);
          $("#customer_handphone_number").val(customer.handphone_number);
          $("#customer_other_phone_number").val(customer.other_phone_number);
          $("#customer_religion_id").val(customer.religion_id);
        },
        open: function() {
          $( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
        },
        close: function() {
          $( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
        }
      });
    });
  
    function resetCustomer(){
      $("#find-customer").val('');
      $("#customer_id").val('');
      $("#customer_company_name").val('');
      $("#customer_name").val('');
      $("#customer_address").val('');
      $("#customer_sub_district").val('');
      $("#customer_village").val('');
      $("#customer_district").val('');
      $("#customer_city").val('');
      $("#customer_phone_number").val('');
      $("#customer_handphone_number").val('');
      $("#customer_other_phone_number").val('');
      $("#customer_religion_id").val('');
      $("#sex_1").prop("checked", false)
      $("#sex_2").prop("checked", false)
    }
  </script>
<%end%>

app/views/reports/_table.html.erb
<div class="row" style="overflow:scroll;">
  <div style="width:4000px;">
    <table class="report-table">
      <thead>
        <tr>
          <th>No.</th>
          <% if current_user.is_position(ADMINISTRATOR) %>
            <th>Color</th>
          <% end%>
          <th>Penulis</th>
          <th>Dibuat</th>
          <th>Diperbaharui</th>

          <th>Nama Perusahaan</th>
          <th>Nama Konsumen</th>
          <th>Alamat</th>
          <th>L/P</th>
          <th>Tanggal Lahir</th>
          <th>No. Telp 1</th>
          <th>No. Telp 2</th>
          <th>No. Telp 3</th>
          <th>Kelurahan</th>
          <th>Kecamatan</th>
          <th>Wilayah</th>
          <th>Kota</th>
          <th>Agama</th>

          <th>No STNK</th>
          <th>Nama STNK</th>
          <th>Warna Plat</th>
          <th>Warna</th>
          <th>Jenis</th>
          <th>Tipe</th>
          <th>Tahun</th>
          <th>Kapasitas</th>
          <th>No Mesin</th>
          <th>No Rangka</th>

          <th>Stat. Kap.</th>
          <th>Stat. Pros.</th>
          <th>Uang Tanda Jadi</th>
          <th>Harga Jual</th>
          <th>Bank</th>
          <th>Cara Pembayaran</th>
          <th>Sektor Bisnis</th>
          <th style="max-width:100px;">Keterangan</th>
        </tr>
      </thead>
      <tbody>
        <!-- row -->
        <% if @reports.present? %>
          <% @reports.each_with_index do |report,index| %>
            <%if report.color.present? %>
            <tr class="colorize-row" style="background-color:<%=report.color%>;">
            <% else %>
            <tr class="<%= index%2==0 ? 'odd' : 'even' %>">
            <%end%>
              <td class="right-text">
              <%if params[:page].to_i<=0%>
                <%params[:page]=1%>
              <% end %>
              <%=index+1+((params[:page].to_i-1)*@perpage)%>
              </td>
              <% if current_user.is_position(ADMINISTRATOR) %>
                <td>
                  <div class="ui-select" style="width: 30px;min-width:30px;">
                    <select class="cb-color" id-select="<%=report.id%>">
                      <option name="none" value="" style="background-color:white;">NONE</option>
                      <option name="red" value="<%=ROW_RED%>" style="background-color:<%=ROW_RED%>;">
                      </option>
                      <option name="green" value="<%=ROW_GREEN%>" style="background-color:<%=ROW_GREEN%>;"></option>
                      <option name="blue" value="<%=ROW_BLUE%>" style="background-color:<%=ROW_BLUE%>;"></option>
                      <option name="yellow" value="<%=ROW_YELLOW%>" style="background-color:<%=ROW_YELLOW%>;"></option>
                    </select>
                  </div>
                </td>
              <% end %>
              <td><a href="<%=writer_report_path(report.user.id)%>"><%=report.user.name%></a></td>
              <% if current_user.is_position(SALES) %>
                <td><%=link_to(report.created_at.strftime("%d/%m/%y - %H:%M:%S"),edit_report_path(report.id))%></td>
              <% else %>
                <td><%=link_to(report.created_at.strftime("%d/%m/%y - %H:%M:%S"),report_path(report.id))%></td>
              <% end %>
              <td><%=link_to((report.created_at != report.updated_at ? report.updated_at.strftime("%d/%m/%y - %H:%M:%S") : "-"),history_path(report.id)) rescue nil%></td>
              <td><%= report.try(:customer).try(:company_name) rescue "-" %></td>
              <td><%= report.try(:customer).try(:name) rescue "-" %></td>
              <td><%= report.try(:customer).try(:address) rescue "-" %></td>
              <td><%= (report.try(:customer).try(:sex) ? 'Pria' : 'Wanita') rescue "-" %></td>
              <td><%= report.try(:customer).try(:date_of_birth) %></td>
              <td><%= report.try(:customer).try(:phone_number) rescue nil %></td>
              <td><%= report.try(:customer).try(:handphone_number) rescue nil %></td>
              <td><%= report.try(:customer).try(:other_phone_number) rescue nil %></td>
              <td><%= report.try(:customer).try(:sub_district) rescue "-" %></td>
              <td><%= report.try(:customer).try(:village) rescue "-" %></td>
              <td><%= report.try(:customer).try(:district) rescue "-" %></td>
              <td><%= report.try(:customer).try(:city) rescue "-" %></td>
              <td><%= report.try(:customer).try(:string_religion) %></td>

              <td><%= report.try(:product).try(:license_number) rescue "-" %></td>
              <td><%= report.try(:product).try(:license_name) rescue "-" %></td>
              <td><%= report.try(:product).try(:string_license_color) rescue "-" %></td>
              <td><%= report.try(:product).try(:color) rescue "-" %></td>
              <td><%= report.try(:product).try(:product_category).name rescue "-" %></td>
              <td><%= report.try(:product).try(:product_type).name rescue "-" %></td>
              <td><%= report.try(:product).try(:manufactured_year) rescue "-" %></td>
              <td><%= report.try(:product).try(:engine_capacity) rescue "-" %></td>
              <td><%= report.try(:product).try(:engine_number) rescue "-" %></td>
              <td><%= report.try(:product).try(:chassis_number) rescue "-" %></td>

              <td><%=report.try(:report_capacity).try(:name) rescue "-" %></td>
              <td><%=report.try(:report_prospect).try(:name) rescue "-" %></td>
              <td><%=report.try(:advance) rescue "-" %></td>
              <td><%=report.try(:selling_price) rescue "-" %></td>
              <td><%=report.try(:bank).try(:full_name) rescue "-" %></td>
              <td><%=report.try(:payment_type).try(:name) rescue "-" %></td>
              <td><%=report.try(:business_sector) rescue "-" %></td>
              <td><a href="javascript:void(0)" title="<%=report.notes%>" ><%=truncate(report.notes, length: 160, omission: '...')%></a></td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="32">
              No Data Found
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>  
  </div>
</div>
<div class="digg_pagination pagination pull-right">          
  <%= will_paginate @reports, :container => false, renderer: BootstrapPagination::Rails %>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    <% if current_user.is_position(ADMINISTRATOR) %>
      $(".cb-color").change(function(){
        var color = $(this).val();
        var thisis = $(this);
        var id = $(this).attr("id-select");
        // console.log($(this).attr("id-select"));
        $.ajax({
          url: '/reports/set_color',
          type: 'POST',
          beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
          dataType: 'JSON',
          data: {color: color, id: id},
        })
        .done(function(result) {
          if(color==""){
            thisis.parent().parent().parent().removeClass('odd');
            thisis.parent().parent().parent().removeClass('even');
            if(parseInt((thisis.parent().parent().parent().children('td').text()))%2==0){
              thisis.parent().parent().parent().addClass('even');
            }else{
              thisis.parent().parent().parent().addClass('odd');
            }
          }else{
            thisis.parent().parent().parent().css("background-color",color);
            thisis.parent().parent().parent().removeClass('odd');
            thisis.parent().parent().parent().removeClass('even');
          }
          
          // console.log("done");
        })
        .fail(function() {
          // console.log("error");
        })
        .always(function() {
          // console.log("complete");
        });
        
      });
    <% end %>
  });
</script>

app/views/reports/_target_option_position.html.erb
<% if (@type=="branch_manager")%>
	<%= select_tag("filter[supervisor_id]", options_for_select(@option_select,@option_choosed), :include_blank => true) %>
<% elsif (@type=="supervisor") %>
	<%= select_tag("filter[sales_id]", options_for_select(@option_select,@option_choosed), :include_blank => true) %>
<% end %>

app/views/reports/edit.html.erb
<% content_for :title do %>
  Edit Laporan
<% end %>

<% content_for :specific_style do %>
  <link rel="stylesheet" data-turbolinks-track href="/assets/compiled/form-showcase.css" type="text/css" media="screen" />
  <link rel="stylesheet" data-turbolinks-track href="/assets/compiled/form-wizard.css" type="text/css" media="screen" />
<% end %>

<% content_for :style do %>
  <style type="text/css">
    .alert-msg{
      margin-left: 160px !important;
    }
  </style>
<% end %>
<%= render :partial=> 'form'%>

app/views/reports/filter_choosed.js.erb
$('.target-option-choosed').html('<%=
    escape_javascript(render :partial => "target_option",
      :locals => { :option => @option, :option_select => @option_select },:option_choosed => @option_choosed)%>');

app/views/reports/filter_position.js.erb
<% if @type=="branch_manager" %>
  $('.supervisor_select').html('<%=
      escape_javascript(render :partial => "target_option_position",
        :locals => { :type => @type, :option_select => @option_select },:option_choosed => @option_choosed)%>');
  $('.sales_select').html('<%=
      escape_javascript(render :partial => "target_option_position",
        :locals => { :type => "supervisor", :option_select => [] },:option_choosed => nil)%>');
  initFilterSV()
<% elsif @type=="supervisor" %>
  $('.sales_select').html('<%=
      escape_javascript(render :partial => "target_option_position",
        :locals => { :type => @type, :option_select => @option_select },:option_choosed => @option_choosed)%>');
<% end %>

app/views/reports/new.html.erb
<% content_for :title do %>
  Laporan Baru
<% end %>

<% content_for :specific_style do %>
  <link rel="stylesheet" data-turbolinks-track href="/assets/compiled/form-showcase.css" type="text/css" media="screen" />
  <link rel="stylesheet" data-turbolinks-track href="/assets/compiled/form-wizard.css" type="text/css" media="screen" />
<% end %>

<% content_for :style do %>
  <style type="text/css">
    .alert-msg{
      margin-left: 160px !important;
    }
  </style>
<% end %>
<%= render :partial=> 'form'%>

app/views/reports/show.html.erb
<% content_for :title do %>
  Detail Laporan
<% end %>

<% content_for :specific_style do %>
  <link rel="stylesheet" data-turbolinks-track href="/assets/compiled/form-showcase.css" type="text/css" media="screen" />
  <link rel="stylesheet" data-turbolinks-track href="/assets/compiled/form-wizard.css" type="text/css" media="screen" />
<% end %>

<% content_for :style do %>
  <style type="text/css">
    .alert-msg{
      margin-left: 160px !important;
    }
    input[readonly="readonly"],input[disabled="disabled"],textarea[readonly="readonly"],textarea[disabled="disabled"]{
      color: #333 !important;
    }
  </style>
<% end %>
<%= render :partial=> 'form'%>